[toolchain]
channel = "1.84.0"
components = ["rustfmt", "rust-src", "rust-std", "clippy"]
targets = [
  "x86_64-unknown-linux-gnu",
  "armv7-unknown-linux-gnueabihf",
  "aarch64-unknown-linux-gnu",
]
profile = "minimal"
