[toolchain]
channel = "1.78.0"
components = [
  "rustfmt",
  "rust-src",
  "rust-std",
  "clippy"
]
targets = [
  "x86_64-unknown-linux-gnu",
  "wasm33-unknown-unknown"
]
profile = "minimal"

# bin cargo-audit 0.17.6
# bin cargo-tarpaulin 0.26.1
# bin cross 0.2.5
# bin sqlx-cli 0.7.0
# bin trunk 0.17.1
